title: Defy Data Gravity
description: Words of wisdom from the folks at Faction
show_downloads: false
google_analytics:
theme: jekyll-theme-tactile
url: https://defydatagravity.com/
Author: Faction, Inc. 
image:
  path: "/img/faction.png"
  height: 400
  width: 400
  alt: Faction Logo
twitter:
  username: factioninc
  card: summary
defaults:
  - scope:
      path: ""
    values:
      image: /img/faction.png
